### ISSUE TITLE
Relation-Only Pickers deleting Relations data when nodes open simultaneously

### ISSUE THREAD

**Issue by hfloyd** [uComponents/nuPickers#130]
Well, I had relation pickers working last week (see [Issue #62](https://github.com/uComponents/nuPickers/issues/62)), but am now seeing a data-integrity issue.

I am relating Products to Locations bi-directionally. I have a Relation Type with alias "ProductsAndLocations".

I have created two DataTypes using property editor : nuPickers.XmlCheckBoxPicker.
Both are set to "Content", Relation Mapping is set to "Products and Locations", Save Format is "Relations Only".
* "Relation - Location Product Picker" - Has an Xpath to display Product Nodes
* "Relation - Product Location Picker" - Has Xpath to display Location Nodes

The "Product" doctype has a property using DataType "Relation - Product Location Picker" and the "Location" doctype has a property using "Relation - Location Product Picker". 

When I open a Product node in the Content Tree, the checkbox list renders properly. I can check a Location and click "SAVE & PUBLISH" - but if I then go to the Developer section and open the Relation Type "Products and Locations" - and go to the second tab "Relations" - It says "Count 0" and nothing is displayed.

Sometimes if I go to a different node and make the selection, it will get saved to the relations list, but if I then go back to that node later, it's gone and the relations list is empty again.

With further testing, it seems that if the two different nodes (which are getting related to one another) are "open" simultaneously (in separate browser tabs, or perhaps by different users), the relations data seems to get deleted. It's possible that if Node A is opened, and has no selections for the relations (all checkboxes unchecked), and then Node B is opened somewhere else, and a relation selection to Node A is made and saved, it may or may not get saved properly to the relations table.

I'm not exactly sure when the syncing operation takes place, but it seems that we might need a way for it to recognize whether the relations data has been changed since the node was opened. I can certainly understand that if Node B, with the Node A relation is saved, the data might get saved, but then if Node A is saved (even if changes were only made to a different property), the "empty" selection for the relationship will also be saved - thus deleting the just-created relation. 

Perhaps some way to check for "IsDirty" or some such thing... and only update the relations table if the data has actually been manipulated on the node at that time? And if it hasn't been "touched" - it should be ignored.

**Comment by Hendy** [comment]
Hi @hfloyd I wonder if this is the same bug: https://github.com/uComponents/nuPickers/issues/105#issuecomment-117748391 ? (Relations being deleted when they haven't been changed)

Relations used to be set via AJAX, but there was a bug where if the node hadn't yet been saved, it didn't have an ID to use in the relation - this was fixed by moving the relation setting server-side (in same way as uComponents did), but this change introduced a new bug (link above) which causes relations to be cleared for pickers that weren't changed in a save (that's as I understand it at the moment)

I think if there was a way to check to see if a property has been changed here: https://github.com/uComponents/nuPickers/blob/master/source/nuPickers/Shared/RelationMapping/RelationMappingEvent.cs#L51 it could possibly be a quick fix ? otherwise perhaps it would need to use server-side for when current ID is 0, and then switch to using AJAX just before Umbraco does its save for when the current ID is known.

**Comment by hfloyd** [comment]
Hi @Hendy, Thanks for your thoughts. It might be related... I wonder if it would be possible to somehow use ajax or client-side code to set an "IsDirty" (or IsChanged) flag so that when the node is saved, the server-side code would not overwrite relations data (generally with NULL) UNLESS it was changed in that editing "session"?

**Comment by hfloyd** [comment]
@Hendy. I think that I am most likely experiencing the issue you mentioned. It seems that relations data has been getting randomly deleted from content nodes. (I even changed one of my relation pickers to a "view relations" property, thinking having the pickers on both doctypes was causing the problem.) I will close this issue and we can continue the conversation over on the existing bug.
