### ISSUE TITLE
JSON checkbox picker URL is not used.

### ISSUE THREAD

**Issue by cmwalolo** [uComponents/nuPickers#158]
I tried to use the URL property of the json checkbox picker, but it seems this url is picked insteed : /umbraco/backoffice/nuPickers/JsonDataSourceApi/GetEditorDataItems?currentId=1196&parentId=1195&propertyAlias=fieldsToDisplay which is even not working at all.

Any recommendation to make it work ? or is it just a bug ? :-)

**Comment by Hendy** [comment]
Hi, yes, the URL configuration property for the JSON data source should indeed request the JSON data from that URL.  Can you post the full data type configuration details you are using ?

**Comment by cmwalolo** [comment]
- In fact the json url doesn't accept any querystring => the Server.Map generates a null url ? 
- So for now I need to create a different method for each of my datasources
- The querystring sent to the nuPickerController could be reused as well, but it is not sent either to the defined JSON Datasource.

**Comment by Hendy** [comment]
Hi Cmwalolo,

Could you suggest a way you'd like to see nuPickers handle this use-case ?

Thanks,
Hendy

**Comment by cmwalolo** [comment]
Well if it could already send back the querystring to web api, it could be great :)
The one you use is : currentId=1196&parentId=1195&propertyAlias=fieldsToDisplay

**Comment by Hendy** [comment]
Hi @cmwalolo, 

Sorry for the late reply. It makes a call in the format of  _currentId=1196&parentId=1195&propertyAlias=fieldsToDisplay_ so that the server can identify the specific dataType then get the configured URL, and then make the request (instead of the browser). So it should respect any querystring parameters configured there, but this appears to be the same issue as #140.

What the JSON data source doesn't have yet, is any kind of token replacement (like currentId or typeahead in other data sources).

Can you remember what querystring parameters you wanted to use ?

Thanks,
Hendy
