### ISSUE TITLE
your documentation is garbage

### ISSUE THREAD

**Issue by jabbrowocky** [uComponents/nuPickers#192]
Your documentation is terrible, it explains none of what you have here, none of the features are even remotely touched on. Thanks for nothing.

**Comment by Hendy** [comment]
Hi @jabbrowocky what features are you looking for information on ? There's a [wiki here](https://github.com/uComponents/nuPickers/wiki) with documentation.

**Comment by jabbrowocky** [comment]
I forgot to specify, the property value converter has a single character "I" on the documentation. Also, more explanation of how to use things in a tutorialized fashion would be great. Anyway, I eventually found something in the umbraco forum that allowed me to actually use the xml picker.

**Comment by Hendy** [comment]
Here a link to [using the Property Value Converter](https://github.com/uComponents/nuPickers/wiki/Model)

**Comment by PeteDuncanson** [comment]
Bad day @jabbrowocky?

**Comment by johnseto** [comment]
Think you can do a better job @jabbrowocky ?

**Comment by JimBobSquarePants** [comment]
> Thanks for nothing.

Hi @jabbrowocky 

I imagine that you were probably frustrated when you wrote this - Working under a tight deadline and of course you didn't mean to come across as so aggressive. We've all been there and reacted badly due to the stress, I know I certainly have.

Comments like these are really unhelpful though, as you can imagine. Hendy and others have worked really hard on these components over the years, in their spare time, for no fiscal benefit. 

So please, in future, try to reign it in a little. It can be really quite discouraging and we'd all rather keep everyone involved in this project motivated so they can continue to produce it happy in the knowledge that it is really appreciated and we can continue to benefit from such hard work.
