### ISSUE TITLE
Relation-Only values don't persist on initial save.

### ISSUE THREAD

**Issue by s6admin** [uComponents/nuPickers#77]
When saving a new node for the first time using an XML Picker checkbox list (set to relations-only) the selections are not saved to the database. After the initial save/publish on the node we are able to make the selections again and save them correctly.

Could this be because the node has not yet been created in the database so the relationship does not have the proper ID to reference when attempting to create an entry in the umbracoRelation table?

Thank you!

Umbraco 7.1.8
nuPickers 1.3.0

**Comment by Hendy** [comment]
Hi @s6admin yes, it's exactly that, relations are set by the property editor on save, but when creating a new item, the current.id is reported as 0.

I've started a new branch https://github.com/uComponents/nuPickers/tree/hendy_relations-event to change how relations work, instead of the property editors calling an api controller, it'll be handled with server-side events (as it was with the older multi picker relations)
